version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    env_file: [./config/postgres/development.env]
    ports:
      - 5432:5432

  be:
    image: kanban-be
    restart: always
    env_file: [./config/nest/development.env]
    ports:
      - 8080:3000
    depends_on: [db]
