import SideBar from "@/components/ui/dashboard/SideBar";

export const metadata = {
  title: "Board | Kanban",
  description: "Generated by create next app",
};

function BordLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export default BordLayout;
