import { Inter } from "next/font/google";
import AuthProvider from "../AuthProvider";
import SideBar from "@/components/ui/dashboard/SideBar";

export const metadata = {
  title: "Dashboard | Kanban",
  description: "Generated by create next app",
};

function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <div className="flex overflow-hidden dashboard-wrapper">
        <SideBar />
        <div className="content">{children}</div>
      </div>
    </AuthProvider>
  );
}

export default DashboardLayout;
