import { Inter } from "next/font/google";

import "./globals.css";
import Providers from "./providers";
import ModalRoot from "@/components/modal/ModalRoot";

export const metadata = {
  title: "Kanban",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["500", "600", "700", "800"],
  subsets: ["latin"],
});

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <ModalRoot />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
